# Loading CSV

In [3]:
!unzip '/content/drive/MyDrive/ECS 235 A/Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv.zip'

Archive:  /content/drive/MyDrive/ECS 235 A/Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv.zip
  inflating: Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv

In [162]:
import pandas as pd
data = pd.read_csv('Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv')

In [163]:
data.head()

,Flow ID,Source IP,Source Port,Destination IP,Destination Port,Protocol,Timestamp,Flow Duration,Total Fwd Packets,Total Backward Packets,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,192.168.10.5-104.16.207.165-54865-443-6,104.16.207.165,443,192.168.10.5,54865,6,7/7/2017 3:30,3,2,0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
1,192.168.10.5-104.16.28.216-55054-80-6,104.16.28.216,80,192.168.10.5,55054,6,7/7/2017 3:30,109,1,1,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
2,192.168.10.5-104.16.28.216-55055-80-6,104.16.28.216,80,192.168.10.5,55055,6,7/7/2017 3:30,52,1,1,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
3,192.168.10.16-104.17.241.25-46236-443-6,104.17.241.25,443,192.168.10.16,46236,6,7/7/2017 3:30,34,1,1,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
4,192.168.10.5-104.19.196.102-54863-443-6,104.19.196.102,443,192.168.10.5,54863,6,7/7/2017 3:30,3,2,0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN

In [155]:
src_ip = data[' Source IP'].tolist()
dest_ip = data[' Destination IP'].tolist()

# BlackMarker

In [37]:
def blackMarker(src, dest):
  new_src = ""
  new_dest = ""
  src_split = src.split(".")
  dest_split = dest.split(".")

  for i in range(4):
    new_src += len(src_split[i])*"0"
    if i != 3:
      new_src += "."

  for i in range(4):
    new_dest += len(dest_split[i])*"0"
    if i != 3:
      new_dest += "."

  # new_src = str.encode(new_src)
  # new_dest = str.encode(new_dest)
  return new_src, new_dest

In [38]:
n = len(src_ip)
blackmarker_src = []
blackmarker_dest = []
for i in range(n):
  src, dest = blackMarker(src_ip[i], dest_ip[i])
  blackmarker_src.append(src)
  blackmarker_dest.append(dest)

<class 'str'>
['000.000.00.0', '000.000.00.0', '000.000.00.0', '000.000.00.00', '000.000.00.0', '000.000.00.0', '000.000.00.0', '000.000.00.0', '000.000.00.0', '000.000.00.0', '000.000.00.0', '000.000.00.0', '000.000.00.0', '000.000.00.0', '000.000.00.00', '000.000.00.00', '000.000.00.00', '000.000.00.00', '000.000.00.00', '000.000.00.00', '000.000.00.00', '000.000.00.00', '000.000.00.0', '000.000.00.0', '000.000.00.0', '000.000.00.0', '000.000.00.00', '000.000.00.0', '000.000.00.0', '000.000.00.0', '000.000.00.0', '000.000.00.0', '000.000.00.0', '000.000.00.0', '000.000.00.0', '000.000.00.0', '000.000.00.0', '000.000.00.0', '000.000.00.0', '000.000.00.00', '000.000.00.00', '000.000.00.00', '000.000.00.0', '000.000.00.0', '000.000.00.0', '000.000.00.0', '000.000.00.0', '000.000.00.0', '000.000.00.0', '000.000.00.00', '000.000.00.00', '000.000.00.0', '000.000.00.00', '000.000.00.00', '000.000.00.00', '000.000.00.0', '000.000.00.0', '000.000.00.00', '000.000.00.00', '000.000.00.00', '000.000.00.00', '000.000.00.0', '000.000.00.0', '000.000.00.0', '000.000.00.0', '000.000.00.0', '000.000.00.0', '000.000.00.0', '000.000.00.0', '000.000.00.0', '000.000.00.0', '000.000.00.0', '000.000.00.0', '000.000.00.00', '000.000.00.00', '000.000.00.00', '000.000.00.00', '000.000.00.00', '000.000.000.00', '00.000.000.0', '000.00.000.000', '000.00.000.000', '000.000.00.0', '000.000.00.00', '000.000.0.00', '000.000.0.000', '000.000.0.000', '000.000.00.0', '000.000.00.0', '000.000.00.0', '00.00.000.000', '000.000.00.0', '000.000.000.00', '000.000.0.000', '000.000.00.000', '000.000.00.000', '000.000.00.000', '000.000.00.0', '000.000.00.0', '000.000.00.0']

In [41]:
n = data.columns[3]

data[n] = blackmarker_dest

data.head()

,Flow ID,Source IP,Source Port,Destination IP,Destination Port,Protocol,Timestamp,Flow Duration,Total Fwd Packets,Total Backward Packets,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,192.168.10.5-104.16.207.165-54865-443-6,000.00.000.000,443,000.000.00.0,54865,6,7/7/2017 3:30,3,2,0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
1,192.168.10.5-104.16.28.216-55054-80-6,000.00.00.000,80,000.000.00.0,55054,6,7/7/2017 3:30,109,1,1,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
2,192.168.10.5-104.16.28.216-55055-80-6,000.00.00.000,80,000.000.00.0,55055,6,7/7/2017 3:30,52,1,1,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
3,192.168.10.16-104.17.241.25-46236-443-6,000.00.000.00,443,000.000.00.00,46236,6,7/7/2017 3:30,34,1,1,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
4,192.168.10.5-104.19.196.102-54863-443-6,000.00.000.000,443,000.000.00.0,54863,6,7/7/2017 3:30,3,2,0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN

In [43]:
data.to_csv("/content/drive/MyDrive/ECS 235 A/BlackMarker.csv")

# Permutation Algorithm

In [65]:
#Permutation Algorithm 
import numpy as np
def permutation(src, dest):
  new_src = ""
  new_dest = ""
  src_split = src.split(".")
  dest_split = dest.split(".")

  new_src_array = np.random.permutation(src_split)
  new_dest_array = np.random.permutation(dest_split)
  
  for i in range(4):
    new_src += new_src_array[i]
    if i != 3:
      new_src += "."

  for i in range(4):
    new_dest += new_dest_array[i]
    if i != 3:
      new_dest += "."

  # new_src = str.encode(new_src)
  # new_dest = str.encode(new_dest)
  return new_src, new_dest

new_src, new_dest = permutation(src_ip[0], dest_ip[0])
print('new src', new_src)
print('new dest', new_dest)

new src 165.207.104.16
new dest 5.192.168.10

In [66]:
n = len(src_ip)
permutation_src = []
permutation_dest = []
for i in range(n):
  src, dest = permutation(src_ip[i], dest_ip[i])
  permutation_src.append(src)
  permutation_dest.append(dest)

print('permutation src', permutation_src[0:100])
print('permutation dest', permutation_dest[0:100])

permutation src ['165.104.207.16', '28.216.16.104', '28.216.104.16', '25.17.241.104', '104.196.19.102', '10.104.120.20', '20.10.120.104', '10.120.20.104', '28.104.13.116', '97.104.123.193', '125.104.97.160', '160.125.97.104', '104.125.160.97', '97.37.104.139', '32.104.97.140', '54.141.121.29', '121.54.29.141', '141.121.29.54', '54.29.121.141', '29.141.121.54', '121.54.29.141', '141.54.29.121', '201.37.138.241', '121.144.76.178', '243.163.233.145', '151.0.166.101', '0.249.101.151', '101.151.249.0', '101.108.1.151', '101.5.1.151', '2.130.101.151', '151.2.101.130', '101.2.130.151', '101.2.2.151', '151.101.2.2', '44.151.101.249', '13.163.4.152', '4.152.163.13', '163.2.152.56', '163.152.66.165', '163.152.66.165', '66.152.165.163', '66.169.60.35', '10.217.238.172', '10.217.238.172', '172.238.217.10', '217.10.238.172', '10.217.172.238', '172.238.217.10', '217.1.172.11', '10.172.11.217', '217.12.172.138', '162.172.217.12', '217.172.162.12', '172.98.217.3', '172.217.6.198', '198.217.6.172', '172.217.6.200', '172.206.6.217', '7.132.217.172', '9.232.217.172', '254.241.173.199', '199.254.241.173', '167.39.164.185', '17.185.150.54', '137.185.17.86', '86.17.185.137', '185.86.17.137', '17.137.86.185', '185.17.86.137', '86.17.185.137', '12.10.168.192', '168.192.12.10', '168.12.10.192', '12.168.10.192', '12.10.192.168', '10.168.192.12', '12.10.192.168', '192.12.10.168', '168.12.10.192', '168.14.192.10', '10.192.14.168', '10.192.14.168', '14.168.192.10', '192.168.14.10', '168.192.14.10', '192.14.10.168', '14.168.192.10', '14.168.10.192', '168.192.10.14', '14.10.192.168', '168.192.10.15', '192.168.15.10', '10.16.192.168', '10.192.16.168', '192.10.168.16', '192.168.10.16', '168.10.16.192', '16.192.168.10', '10.168.16.192']
permutation dest ['168.5.10.192', '192.5.10.168', '192.168.10.5', '168.16.10.192', '192.10.5.168', '192.10.5.168', '5.192.168.10', '192.168.10.5', '10.192.8.168', '5.192.10.168', '192.168.5.10', '168.10.192.5', '10.168.5.192', '168.5.192.10', '192.168.16.10', '10.192.25.168', '168.192.10.25', '168.25.192.10', '10.192.168.25', '10.192.25.168', '168.192.10.25', '168.25.192.10', '10.5.168.192', '5.10.168.192', '168.192.5.10', '168.10.192.9', '168.10.16.192', '9.10.192.168', '168.192.5.10', '5.192.168.10', '5.168.10.192', '168.10.5.192', '5.192.168.10', '10.168.5.192', '168.10.192.5', '192.10.9.168', '10.192.168.9', '192.9.168.10', '192.168.9.10', '168.16.192.10', '10.168.16.192', '16.168.10.192', '168.10.192.9', '10.168.8.192', '10.192.8.168', '10.192.168.9', '192.9.10.168', '168.9.192.10', '168.9.10.192', '14.168.10.192', '10.14.168.192', '5.192.10.168', '14.168.192.10', '10.192.168.16', '14.10.192.168', '5.10.192.168', '168.192.5.10', '10.14.192.168', '17.168.192.10', '10.192.168.14', '192.168.10.16', '10.9.168.192', '10.192.168.9', '192.5.168.10', '10.168.192.5', '5.10.192.168', '168.10.5.192', '5.10.192.168', '5.10.192.168', '168.5.10.192', '168.192.5.10', '192.10.168.3', '192.3.168.10', '192.168.50.10', '192.10.168.50', '192.10.50.168', '168.50.10.192', '10.192.50.168', '192.163.97.229', '79.5.127.127', '114.97.104.112', '112.97.104.114', '172.1.217.11', '10.172.217.11', '217.98.172.3', '172.6.200.217', '172.7.132.217', '10.168.192.3', '168.192.3.10', '168.3.192.10', '113.190.53.23', '192.168.3.10', '165.205.174.73', '101.175.0.151', '165.66.163.152', '66.152.163.165', '238.10.217.172', '192.3.10.168', '168.192.3.10', '168.10.3.192']

In [67]:
n = data.columns[1]
data[n] = permutation_src
data.head()

,Flow ID,Source IP,Source Port,Destination IP,Destination Port,Protocol,Timestamp,Flow Duration,Total Fwd Packets,Total Backward Packets,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,192.168.10.5-104.16.207.165-54865-443-6,165.104.207.16,443,192.168.10.5,54865,6,7/7/2017 3:30,3,2,0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
1,192.168.10.5-104.16.28.216-55054-80-6,28.216.16.104,80,192.168.10.5,55054,6,7/7/2017 3:30,109,1,1,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
2,192.168.10.5-104.16.28.216-55055-80-6,28.216.104.16,80,192.168.10.5,55055,6,7/7/2017 3:30,52,1,1,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
3,192.168.10.16-104.17.241.25-46236-443-6,25.17.241.104,443,192.168.10.16,46236,6,7/7/2017 3:30,34,1,1,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
4,192.168.10.5-104.19.196.102-54863-443-6,104.196.19.102,443,192.168.10.5,54863,6,7/7/2017 3:30,3,2,0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN

In [68]:
n = data.columns[3]
data[n] = permutation_dest
data.head()

,Flow ID,Source IP,Source Port,Destination IP,Destination Port,Protocol,Timestamp,Flow Duration,Total Fwd Packets,Total Backward Packets,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,192.168.10.5-104.16.207.165-54865-443-6,165.104.207.16,443,168.5.10.192,54865,6,7/7/2017 3:30,3,2,0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
1,192.168.10.5-104.16.28.216-55054-80-6,28.216.16.104,80,192.5.10.168,55054,6,7/7/2017 3:30,109,1,1,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
2,192.168.10.5-104.16.28.216-55055-80-6,28.216.104.16,80,192.168.10.5,55055,6,7/7/2017 3:30,52,1,1,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
3,192.168.10.16-104.17.241.25-46236-443-6,25.17.241.104,443,168.16.10.192,46236,6,7/7/2017 3:30,34,1,1,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
4,192.168.10.5-104.19.196.102-54863-443-6,104.196.19.102,443,192.10.5.168,54863,6,7/7/2017 3:30,3,2,0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN

# Truncated Algorithm

In [146]:
import numpy as np

def setToZero(arr, num):
  ind = 3 - (num // 8)
  mod = num % 8
  for i in range(ind+1, 4):
    arr[i] = 0
  mask = ~((1 << mod)-1)
  arr[ind] &= mask
  return arr
def truncation(src, dest, n):
  new_src = ""
  new_dest = ""
  src_split = src.split(".")
  dest_split = dest.split(".")

  src_split = [int(x) for x in src_split]
  dest_split = [int(x) for x in dest_split]
  src_split = setToZero(src_split, n)
  dest_split = setToZero(dest_split, n)
  
  src_split = [str(x) for x in src_split]
  dest_split = [str(x) for x in dest_split]

  for i in range(4):
    new_src += src_split[i]
    if i != 3:
      new_src += "."

  for i in range(4):
    new_dest += dest_split[i]
    if i != 3:
      new_dest += "."

  # new_src = str.encode(new_src)
  # new_dest = str.encode(new_dest)
  return new_src, new_dest

new_src, new_dest = truncation(src_ip[0], dest_ip[0], 12)
print('new src', new_src)
print('new dest', new_dest)

new src 104.16.192.0
new dest 192.168.0.0

In [156]:
n = len(src_ip)
truncated_src = []
truncated_dest = []
for i in range(n):
  src, dest = truncation(src_ip[i], dest_ip[i], 20)
  truncated_src.append(src)
  truncated_dest.append(dest)

print('truncated src', truncated_src[0:100])
print('truncated dest', truncated_dest[0:100])

truncated src ['104.16.0.0', '104.16.0.0', '104.16.0.0', '104.16.0.0', '104.16.0.0', '104.16.0.0', '104.16.0.0', '104.16.0.0', '104.16.0.0', '104.96.0.0', '104.96.0.0', '104.96.0.0', '104.96.0.0', '104.96.0.0', '104.96.0.0', '121.16.0.0', '121.16.0.0', '121.16.0.0', '121.16.0.0', '121.16.0.0', '121.16.0.0', '121.16.0.0', '138.192.0.0', '144.64.0.0', '145.240.0.0', '151.96.0.0', '151.96.0.0', '151.96.0.0', '151.96.0.0', '151.96.0.0', '151.96.0.0', '151.96.0.0', '151.96.0.0', '151.96.0.0', '151.96.0.0', '151.96.0.0', '152.160.0.0', '152.160.0.0', '152.160.0.0', '152.160.0.0', '152.160.0.0', '152.160.0.0', '169.48.0.0', '172.208.0.0', '172.208.0.0', '172.208.0.0', '172.208.0.0', '172.208.0.0', '172.208.0.0', '172.208.0.0', '172.208.0.0', '172.208.0.0', '172.208.0.0', '172.208.0.0', '172.208.0.0', '172.208.0.0', '172.208.0.0', '172.208.0.0', '172.208.0.0', '172.208.0.0', '172.208.0.0', '173.240.0.0', '173.240.0.0', '185.160.0.0', '185.48.0.0', '185.80.0.0', '185.80.0.0', '185.80.0.0', '185.80.0.0', '185.80.0.0', '185.80.0.0', '192.160.0.0', '192.160.0.0', '192.160.0.0', '192.160.0.0', '192.160.0.0', '192.160.0.0', '192.160.0.0', '192.160.0.0', '192.160.0.0', '192.160.0.0', '192.160.0.0', '192.160.0.0', '192.160.0.0', '192.160.0.0', '192.160.0.0', '192.160.0.0', '192.160.0.0', '192.160.0.0', '192.160.0.0', '192.160.0.0', '192.160.0.0', '192.160.0.0', '192.160.0.0', '192.160.0.0', '192.160.0.0', '192.160.0.0', '192.160.0.0', '192.160.0.0', '192.160.0.0']
truncated dest ['192.160.0.0', '192.160.0.0', '192.160.0.0', '192.160.0.0', '192.160.0.0', '192.160.0.0', '192.160.0.0', '192.160.0.0', '192.160.0.0', '192.160.0.0', '192.160.0.0', '192.160.0.0', '192.160.0.0', '192.160.0.0', '192.160.0.0', '192.160.0.0', '192.160.0.0', '192.160.0.0', '192.160.0.0', '192.160.0.0', '192.160.0.0', '192.160.0.0', '192.160.0.0', '192.160.0.0', '192.160.0.0', '192.160.0.0', '192.160.0.0', '192.160.0.0', '192.160.0.0', '192.160.0.0', '192.160.0.0', '192.160.0.0', '192.160.0.0', '192.160.0.0', '192.160.0.0', '192.160.0.0', '192.160.0.0', '192.160.0.0', '192.160.0.0', '192.160.0.0', '192.160.0.0', '192.160.0.0', '192.160.0.0', '192.160.0.0', '192.160.0.0', '192.160.0.0', '192.160.0.0', '192.160.0.0', '192.160.0.0', '192.160.0.0', '192.160.0.0', '192.160.0.0', '192.160.0.0', '192.160.0.0', '192.160.0.0', '192.160.0.0', '192.160.0.0', '192.160.0.0', '192.160.0.0', '192.160.0.0', '192.160.0.0', '192.160.0.0', '192.160.0.0', '192.160.0.0', '192.160.0.0', '192.160.0.0', '192.160.0.0', '192.160.0.0', '192.160.0.0', '192.160.0.0', '192.160.0.0', '192.160.0.0', '192.160.0.0', '192.160.0.0', '192.160.0.0', '192.160.0.0', '192.160.0.0', '192.160.0.0', '192.224.0.0', '79.112.0.0', '104.96.0.0', '104.96.0.0', '172.208.0.0', '172.208.0.0', '172.208.0.0', '172.208.0.0', '172.208.0.0', '192.160.0.0', '192.160.0.0', '192.160.0.0', '23.48.0.0', '192.160.0.0', '205.160.0.0', '151.96.0.0', '152.160.0.0', '152.160.0.0', '172.208.0.0', '192.160.0.0', '192.160.0.0', '192.160.0.0']

In [157]:
n = data.columns[1]
data[n] = truncated_src
data.head()

,Flow ID,Source IP,Source Port,Destination IP,Destination Port,Protocol,Timestamp,Flow Duration,Total Fwd Packets,Total Backward Packets,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,192.168.10.5-104.16.207.165-54865-443-6,104.16.0.0,443,192.168.10.5,54865,6,7/7/2017 3:30,3,2,0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
1,192.168.10.5-104.16.28.216-55054-80-6,104.16.0.0,80,192.168.10.5,55054,6,7/7/2017 3:30,109,1,1,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
2,192.168.10.5-104.16.28.216-55055-80-6,104.16.0.0,80,192.168.10.5,55055,6,7/7/2017 3:30,52,1,1,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
3,192.168.10.16-104.17.241.25-46236-443-6,104.16.0.0,443,192.168.10.16,46236,6,7/7/2017 3:30,34,1,1,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
4,192.168.10.5-104.19.196.102-54863-443-6,104.16.0.0,443,192.168.10.5,54863,6,7/7/2017 3:30,3,2,0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN

In [158]:
n = data.columns[3]
data[n] = truncated_dest
data.head()

,Flow ID,Source IP,Source Port,Destination IP,Destination Port,Protocol,Timestamp,Flow Duration,Total Fwd Packets,Total Backward Packets,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,192.168.10.5-104.16.207.165-54865-443-6,104.16.0.0,443,192.160.0.0,54865,6,7/7/2017 3:30,3,2,0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
1,192.168.10.5-104.16.28.216-55054-80-6,104.16.0.0,80,192.160.0.0,55054,6,7/7/2017 3:30,109,1,1,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
2,192.168.10.5-104.16.28.216-55055-80-6,104.16.0.0,80,192.160.0.0,55055,6,7/7/2017 3:30,52,1,1,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
3,192.168.10.16-104.17.241.25-46236-443-6,104.16.0.0,443,192.160.0.0,46236,6,7/7/2017 3:30,34,1,1,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
4,192.168.10.5-104.19.196.102-54863-443-6,104.16.0.0,443,192.160.0.0,54863,6,7/7/2017 3:30,3,2,0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN

In [159]:
data[' Source IP'] = data[' Source IP'].str.replace('.','0')
data[' Destination IP'] = data[' Destination IP'].str.replace('.','0')
data[' Source IP'] = pd.to_numeric(data[' Source IP'])
data[' Destination IP'] = pd.to_numeric(data[' Destination IP'])

data = data.drop(columns=['Flow ID', ' Timestamp'])

<ipython-input-159-eeb8335d7521>:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  data[' Source IP'] = data[' Source IP'].str.replace('.','0')
<ipython-input-159-eeb8335d7521>:2: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  data[' Destination IP'] = data[' Destination IP'].str.replace('.','0')

In [160]:
data.shape

(225745, 83)

In [161]:
data.to_csv("/content/drive/MyDrive/ECS 235 A/truncation_20.csv")

# Randomizer

In [169]:
import random

def randomAlgo():
  new_src = ""
  new_dest = ""

  for i in range(4):
    num = random.SystemRandom().randint(1, 254)
    new_src += str(num)
    if i != 3:
      new_src += "."

  for i in range(4):
    num = random.SystemRandom().randint(1, 254)
    new_dest += str(num)
    if i != 3:
      new_dest += "."


  # new_src = str.encode(new_src)
  # new_dest = str.encode(new_dest
  return new_src, new_dest

new_src, new_dest = randomAlgo()
print(new_src)
print(new_dest)

168.172.113.5
144.39.128.94

In [171]:
n = len(src_ip)
random_src = []
random_dest = []
for i in range(n):
  src, dest = randomAlgo()
  random_src.append(src)
  random_dest.append(dest)

print('random src', random_src[0:100])
print('random dest', random_dest[0:100])

random src ['196.80.32.225', '249.35.75.186', '13.98.173.197', '9.53.59.173', '113.72.164.218', '70.194.15.165', '230.39.65.202', '129.227.156.200', '73.199.125.4', '227.162.207.231', '220.150.187.208', '179.252.107.96', '58.99.105.217', '60.159.145.15', '120.23.121.107', '30.133.225.231', '143.110.108.203', '20.93.19.113', '76.101.121.250', '85.154.82.12', '59.59.59.8', '218.41.248.64', '33.63.38.144', '116.67.118.105', '145.40.101.245', '12.107.254.15', '222.61.24.112', '92.111.184.93', '12.68.114.87', '153.92.66.86', '2.123.81.75', '8.210.98.116', '162.213.60.127', '84.124.73.228', '196.131.6.135', '161.162.97.130', '167.84.127.218', '111.129.96.107', '65.67.22.166', '52.155.197.77', '81.18.142.151', '142.179.136.215', '37.154.37.173', '197.61.84.137', '57.226.156.102', '16.227.177.89', '140.237.127.189', '87.148.192.221', '88.99.162.87', '109.177.241.110', '149.172.61.81', '135.164.172.97', '193.229.239.213', '165.40.235.179', '210.173.245.240', '118.74.99.196', '190.72.35.144', '134.181.252.248', '25.170.24.21', '213.120.123.49', '74.134.135.190', '113.23.246.203', '207.187.88.55', '147.120.193.60', '195.253.250.181', '39.183.134.250', '224.3.129.203', '207.119.189.27', '58.10.231.139', '24.85.25.224', '53.204.195.69', '191.22.130.105', '90.231.111.202', '235.179.105.214', '117.21.33.150', '109.21.212.159', '133.169.237.151', '58.91.63.46', '226.128.242.153', '50.82.77.146', '151.159.152.177', '148.185.148.50', '128.26.229.207', '70.249.151.91', '38.67.163.5', '36.207.59.155', '236.107.138.154', '241.8.18.115', '232.233.214.97', '134.103.151.1', '96.87.166.69', '245.219.173.120', '249.21.232.243', '5.30.138.228', '234.76.63.45', '97.147.149.29', '147.247.155.66', '44.243.145.234', '239.105.166.30', '79.11.244.36']
random dest ['162.194.190.194', '33.25.111.156', '234.223.30.105', '77.17.250.209', '207.111.247.130', '41.189.155.171', '73.25.156.10', '7.19.152.22', '181.94.250.43', '234.75.1.40', '126.245.73.134', '53.84.163.89', '53.74.33.225', '157.186.154.4', '70.90.198.53', '98.147.41.204', '46.199.29.232', '124.2.37.81', '228.59.37.18', '133.120.104.184', '165.141.50.76', '199.166.59.27', '15.175.197.99', '219.115.158.86', '85.240.167.52', '137.175.65.109', '203.15.181.173', '99.21.106.80', '142.239.90.107', '192.75.123.97', '76.38.209.131', '239.171.56.199', '179.117.219.15', '19.15.136.129', '198.208.34.131', '199.138.68.226', '194.103.43.135', '219.189.229.30', '246.135.249.228', '3.130.27.146', '104.132.87.14', '199.121.30.139', '27.181.87.209', '251.85.48.58', '50.179.88.115', '60.98.252.194', '148.16.177.148', '12.151.192.234', '34.123.105.229', '78.54.88.172', '164.127.155.12', '81.239.80.40', '104.32.50.4', '105.65.187.111', '20.161.32.47', '112.130.221.169', '170.81.130.144', '15.153.227.253', '78.109.181.140', '117.105.44.75', '173.70.100.19', '195.2.165.87', '92.60.172.72', '65.102.206.95', '37.251.67.95', '145.44.134.80', '218.84.221.184', '55.165.166.203', '144.162.96.49', '182.206.90.39', '236.205.234.101', '55.196.118.102', '217.87.122.40', '218.154.68.141', '252.75.243.121', '189.124.44.102', '144.175.112.195', '247.196.48.104', '117.100.115.3', '185.13.110.37', '112.193.245.74', '9.203.250.149', '77.187.20.9', '186.66.105.152', '78.192.246.147', '202.244.230.16', '22.45.216.217', '65.237.251.156', '93.71.83.28', '234.37.1.139', '201.108.23.172', '235.171.135.181', '240.140.217.209', '226.192.190.75', '198.138.165.10', '76.31.160.241', '90.34.24.3', '56.33.181.84', '204.142.224.57', '186.17.201.18']

In [172]:
n = data.columns[1]
data[n] = random_src
data.head()

,Flow ID,Source IP,Source Port,Destination IP,Destination Port,Protocol,Timestamp,Flow Duration,Total Fwd Packets,Total Backward Packets,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,192.168.10.5-104.16.207.165-54865-443-6,196.80.32.225,443,192.168.10.5,54865,6,7/7/2017 3:30,3,2,0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
1,192.168.10.5-104.16.28.216-55054-80-6,249.35.75.186,80,192.168.10.5,55054,6,7/7/2017 3:30,109,1,1,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
2,192.168.10.5-104.16.28.216-55055-80-6,13.98.173.197,80,192.168.10.5,55055,6,7/7/2017 3:30,52,1,1,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
3,192.168.10.16-104.17.241.25-46236-443-6,9.53.59.173,443,192.168.10.16,46236,6,7/7/2017 3:30,34,1,1,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
4,192.168.10.5-104.19.196.102-54863-443-6,113.72.164.218,443,192.168.10.5,54863,6,7/7/2017 3:30,3,2,0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN

In [173]:
n = data.columns[3]
data[n] = random_dest
data.head()

,Flow ID,Source IP,Source Port,Destination IP,Destination Port,Protocol,Timestamp,Flow Duration,Total Fwd Packets,Total Backward Packets,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,192.168.10.5-104.16.207.165-54865-443-6,196.80.32.225,443,162.194.190.194,54865,6,7/7/2017 3:30,3,2,0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
1,192.168.10.5-104.16.28.216-55054-80-6,249.35.75.186,80,33.25.111.156,55054,6,7/7/2017 3:30,109,1,1,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
2,192.168.10.5-104.16.28.216-55055-80-6,13.98.173.197,80,234.223.30.105,55055,6,7/7/2017 3:30,52,1,1,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
3,192.168.10.16-104.17.241.25-46236-443-6,9.53.59.173,443,77.17.250.209,46236,6,7/7/2017 3:30,34,1,1,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
4,192.168.10.5-104.19.196.102-54863-443-6,113.72.164.218,443,207.111.247.130,54863,6,7/7/2017 3:30,3,2,0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN

In [174]:
data[' Source IP'] = data[' Source IP'].str.replace('.','0')
data[' Destination IP'] = data[' Destination IP'].str.replace('.','0')
data[' Source IP'] = pd.to_numeric(data[' Source IP'])
data[' Destination IP'] = pd.to_numeric(data[' Destination IP'])

data = data.drop(columns=['Flow ID', ' Timestamp'])

<ipython-input-174-eeb8335d7521>:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  data[' Source IP'] = data[' Source IP'].str.replace('.','0')
<ipython-input-174-eeb8335d7521>:2: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  data[' Destination IP'] = data[' Destination IP'].str.replace('.','0')

In [175]:
data.to_csv("/content/drive/MyDrive/ECS 235 A/random_Algo.csv")

# Reverse Truncation

In [ ]:
import numpy as np

def setToZero(arr, num):
  ind = (num // 8)
  mod = num % 8
  for i in range(0, ind):
    arr[i] = 0
  mod = 32 - mod
  mask = ((1 << mod)-1)
  print('mask', mask)
  arr[ind] &= mask
  return arr
  
def rev_truncation(src, dest, n):
  new_src = ""
  new_dest = ""
  src_split = src.split(".")
  dest_split = dest.split(".")

  src_split = [int(x) for x in src_split]
  dest_split = [int(x) for x in dest_split]
  src_split = setToZero(src_split, n)
  dest_split = setToZero(dest_split, n)
  
  src_split = [str(x) for x in src_split]
  dest_split = [str(x) for x in dest_split]

  for i in range(4):
    new_src += src_split[i]
    if i != 3:
      new_src += "."

  for i in range(4):
    new_dest += src_split[i]
    if i != 3:
      new_dest += "."

  # new_src = str.encode(new_src)
  # new_dest = str.encode(new_dest)
  return new_src, new_dest

print('src', src)
print('dest', dest)
new_src, new_dest = rev_truncation(src, dest, 16)
print('new src', new_src)
print('new dest', new_dest)

In [ ]:
n = len(src_ip)
rev_src = []
rev_dest = []
for i in range(n):
  src, dest = rev_truncation(src, dest, 16)
  rev_src.append(src)
  rev_dest.append(dest)

print('random src', rev_src[0:100])
print('random dest', rev_dest[0:100])